apiVersion: apps/v1
kind: Deployment
metadata:
  name: changeme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: changeme
  template:
    metadata:
      labels:
        app: changeme
    spec:
      containers:
      - name: changeme
        image: colenak.adzkia.web.id/demo/image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: changeme
  labels:
    app: changeme
spec:
  type: LoadBalancer
  ports:
    - name: changeme
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: changeme
